<?php
use Laminas\Json\Json;

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

echo "<pre>\n";
$current = 0;
foreach ($this->__vars as $name => $var) {
    $previous = $current - 1;
    $next = $current + 1;
    echo "<HR><a id='$current'></a>\n<a href='#$next'>[Next]</a> <a href='#$previous'>[Previous]</a> <h1>$name</h1>\n";
    echo Json::prettyPrint($var, array('indent' => '    '));
    $current++;
}
echo "</pre>";
?>