<div class="row">
<div class="col-md">
<div class="card mb-4">
<?php
$this->form->setAttribute('action', $this->url('box', ['action' => 'upload']));
$this->form->prepare();
echo $this->form()->openTag($form);
?>
        	<div class="card-header d-flex justify-content-between">
        		<div>
        			<b><?php echo $this->template_name; ?></b>
        		</div>
        	</div>
        	
        	<div class="card-body">
        	<?php echo $this->formCollection($this->form); ?>
        	</div>
        <?php echo $this->form()->closeTag($this->form); ?>
        </div>
    </div>
</div>