<?php
use Laminas\Form\Element\Button;
?>

<?php
$this->form->setAttribute('action', $this->url('application', ['action' => 'form']));
$this->form->prepare();

/**
 * @var Button $button
 */
$button = $this->form->get('BUTTON');
$url = $this->url('box', ['action' => 'refresh_metadata_templates']);
$button->setAttribute('onclick', "window.open('$url')");

echo $this->form()->openTag($form);
?>

<div class="row">
	<div class="col-md">
        <div class="card mb-4">
        	<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Metadata Templates</b>
        		</div>
        	</div>
        	<div class="card-body">
        		<?php echo $this->bsFormSelectButtonRow($this->form->get('TEMPLATE'), $this->form->get('BUTTON'), NULL, NULL, 'bsFormSelectButton'); ?>
        		<?php echo $this->formRow($this->form->get('FILE_ID')); ?>
        		<?php echo $this->formRow($this->form->get('SECURITY')); ?>
        		<?php echo $this->formRow($this->form->get('SUBMIT')); ?>
        	</div>
        
        </div>
    </div>
</div>

<div class="row">
	<div class="col-md" style="max-height: 512px; overflow-y: auto;">
		<div class="card mb-4">
			<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Uploaded Files</b>
        		</div>
        		<div>
        			<a href="" class="btn btn-primary btn-rounded btn-sm" data-bs-toggle="modal" data-bs-target="#modalLoginForm">Add File</a>
        		</div>
        	</div>
        	<div class="card-body">
        		<ul>
        			<?php foreach ($previews as $id => $name) : ?>
        			<li role="button" onclick="document.getElementById('preview').src = i<?=$id?>; document.getElementById('FILE_ID').value = <?=$id?>;"><?php echo $name; ?></li>
        			
        			<?php endforeach; ?>
        		</ul>
        	</div>
		</div>
	</div>
	<div class="col-md">
		<div class="card mb-4">
			<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Preview</b>
        		</div>
        	</div>
        	<div class="card-body">
        		<img src="" id="preview">
        	</div>
		</div>
	</div>
</div>
<?php echo $this->form()->closeTag($this->form); ?>

<?php echo $this->partial('form/upload-file-form.phtml', ['form' => $upload_form]); ?>

<script type="text/javascript">
<?php foreach ($previews as $id => $name) : ?>
var i<?=$id?> = "data:image/jpg;base64,<?=$images[$id]?>";
<?php endforeach; ?>
</script>